#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

# git submodule update --init --recursive
# echo "[INFO] submodules initialized"

$ROOT/scripts/install_mpls
mkdir -p $ROOT/figures
mkdir -p $ROOT/results
mkdir -p $ROOT/small/figures
mkdir -p $ROOT/small/results
