#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=$ROOT/scripts/gencmds
RUN=$ROOT/scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/results
RESULTS=$ROOT/results/$NOW

rm -f $ROOT/mpl/bin/*.bin

( \
  $GEN $@ $ROOT/exp.json \
) \
| $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
